version: "3"

services:
  todo-list:
    container_name: todo-list
    build:
      context: ./.docker/build/todo-list
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    tty: true
    ports:
      - 3001:3001
